# Generated by Django 4.2.5 on 2023-10-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pacientes',
            name='paciente_id',
        ),
    ]
