# Generated by Django 4.2.5 on 2023-10-01 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0003_especialidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicos',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.especialidad'),
        ),
    ]
