# Generated by Django 4.2.5 on 2023-10-28 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0005_citas_area'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cirugias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
    ]
