# Generated by Django 4.2.5 on 2023-10-28 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0006_cirugias'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalaOperaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('estado', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Cirugias',
        ),
    ]
