# Generated by Django 4.2.5 on 2023-11-18 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0008_tecnicos_enfermeros'),
    ]

    operations = [
        migrations.CreateModel(
            name='SeguroPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
      
    ]
