# Generated by Django 4.2.5 on 2023-11-18 03:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0009_seguropaciente_pacientes_seguro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pacientes',
            name='seguro',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='integrador.seguropaciente'),
        ),
    ]
