# Generated by Django 4.2.5 on 2023-11-18 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0010_pacientes_seguro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cobertura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descuento', models.DecimalField(decimal_places=2, max_digits=5)),
                ('Especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.especialidad')),
            ],
        ),
    ]
