# Generated by Django 4.2.5 on 2023-12-02 03:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0012_beneficiosseguro'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recetas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=50)),
                ('dosis', models.CharField(max_length=50)),
                ('observacion', models.CharField(max_length=200)),
                ('cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.citas')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.medicos')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.pacientes')),
            ],
        ),
        migrations.CreateModel(
            name='EquipoMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('observacion', models.CharField(max_length=200)),
                ('enfermeros', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.enfermeros')),
                ('medicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.medicos')),
                ('pacientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.pacientes')),
                ('sala', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.salaoperaciones')),
                ('tecnicos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integrador.tecnicos')),
            ],
        ),
    ]
