# Generated by Django 4.2.5 on 2023-12-02 18:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integrador', '0016_horariomedico'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicos',
            name='horario',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='integrador.horariomedico'),
            preserve_default=False,
        ),
    ]
